# Pykarambola Demo

This notebook demonstrates how to use **pykarambola** to compute Minkowski functionals and tensors on 3D triangulated surfaces.

## What are Minkowski tensors?

Minkowski tensors are a family of morphological measures that fully characterise the geometry and topology of a body in 3D:

| Functional | Meaning | Rank |
|---|---|---|
| w000 | Volume | scalar |
| w100 | Surface area | scalar |
| w200 | Integrated mean curvature | scalar |
| w300 | Euler characteristic | scalar |
| w010, w110, w210, w310 | Position-weighted vectors | vector |
| w020, w120, w220, w320, w102, w202 | Rank-2 tensors (anisotropy) | 3×3 matrix |

In [1]:
import numpy as np
import pykarambola

## 1. Quick start: compute functionals from numpy arrays

The simplest way to use pykarambola is via `minkowski_tensors()`, which takes vertex and face arrays directly.

In [2]:
# Define a simple box (2 x 3 x 4) centred at the origin
a, b, c = 2.0, 3.0, 4.0
ha, hb, hc = a / 2, b / 2, c / 2

verts = np.array([
    [-ha, -hb, -hc],  # 0
    [ ha, -hb, -hc],  # 1
    [ ha,  hb, -hc],  # 2
    [-ha,  hb, -hc],  # 3
    [-ha, -hb,  hc],  # 4
    [ ha, -hb,  hc],  # 5
    [ ha,  hb,  hc],  # 6
    [-ha,  hb,  hc],  # 7
], dtype=np.float64)

# 12 triangles (2 per face), outward-facing normals
faces = np.array([
    [0, 3, 2], [0, 2, 1],  # -z face
    [4, 5, 6], [4, 6, 7],  # +z face
    [0, 1, 5], [0, 5, 4],  # -y face
    [2, 3, 7], [2, 7, 6],  # +y face
    [0, 4, 7], [0, 7, 3],  # -x face
    [1, 2, 6], [1, 6, 5],  # +x face
], dtype=np.int64)

result = pykarambola.minkowski_tensors(verts, faces)

A = 2 * (a*b + b*c + a*c)  # true surface area = 52
print(f"Volume (w000):               {result['w000']:.4f}  (expected {a*b*c})")
print(f"Surface area (w100):         {result['w100']:.4f}  (expected A/3 = {A/3:.4f}, where A = {A:.0f})")
print(f"Mean curvature (w200):       {result['w200']:.4f}")
print(f"Euler characteristic (w300): {result['w300']:.4f}  (expected 4π/3 ≈ {4*np.pi/3:.4f}; encodes χ=2 via w300 = (2π/3)·χ)")

Volume (w000):               24.0000  (expected 24.0)
Surface area (w100):         17.3333  (expected A/3 = 17.3333, where A = 52)
Mean curvature (w200):       9.4248
Euler characteristic (w300): 4.1888  (expected 4π/3 ≈ 4.1888; encodes χ=2 via w300 = (2π/3)·χ)


### Normalization: the Steiner formula

The factors of 1/3 and 2π/3 throughout pykarambola come from the **Steiner formula** for
parallel bodies. The volume of the ε-dilation K⊕εB expands as a polynomial in ε:

$$V(K \oplus \varepsilon B) = W_0 + 3W_1\varepsilon + 3W_2\varepsilon^2 + W_3\varepsilon^3$$

Matching coefficients gives the **Hadwiger/Blaschke normalization** (d=3):

| ν | binom(3,ν) | Factor | Geometric meaning | Example scalar |
|---|---|---|---|---|
| 0 | 1 | ×1 | volume element | `w000 = V` |
| 1 | 3 | ×1/3 | surface-area element | `w100 = A/3` |
| 2 | 3 | ×1/3 | mean-curvature element | `w200 = M/3` |
| 3 | 1 | ×2π/3 | Gaussian-curvature element | `w300 = (2π/3)·χ` |

> **w300 and the Gauss–Bonnet theorem.** By the Gauss–Bonnet theorem,
> ∫∫ K_G dA = 2πχ, so 2πχ *is* a geometric quantity: the **total Gaussian curvature**
> of the surface. Thus `w300 = (total Gaussian curvature) / 3`.
> For a convex body (χ=2): 2π·2 = 4π, confirming `w300 = 4π/3`.

**This normalization applies uniformly across all tensor ranks.** Every pykarambola
quantity W^{r,s}_ν (r position weights, s normal weights) carries the same 1/binom(3,ν)
factor as its scalar counterpart W^{0,0}_ν:

| ν | Factor | Scalars | Vectors | Rank-2 tensors | Higher-rank tensors |
|---|---|---|---|---|---|
| 0 | ×1 | `w000` | `w010` | `w020` | — |
| 1 | ×1/3 | `w100` | `w110` | `w120`, `w102` | `w103`, `w104` |
| 2 | ×1/3 | `w200` | `w210` | `w220`, `w202` | — |
| 3 | ×2π/3 | `w300` | `w310` | `w320` | — |

**Verification from the box example:** for `w102` (ν=1, rank-2, normal-weighted),
the six faces contribute diag(24, 16, 12) to ∫ n⊗n dA; dividing by 3 gives
diag(8, 5.33, 4) — matching the eigenvalues `[4.000, 5.333, 8.000]` below.
Likewise, Tr(`w102`) = (1/3)·A = `w100`.

## 2. Loading meshes from files

Pykarambola includes parsers for `.poly` (Geomview), `.off`, `.obj`, and `.glb` files.

In [3]:
# Load a .poly file
tri = pykarambola.parse_poly_file('../tests/fixtures/box_a=2_b=3_c=4.poly')

print(f"Vertices: {tri.n_vertices()}")
print(f"Triangles: {tri.n_triangles()}")

Vertices: 8
Triangles: 12


In [4]:
result = pykarambola.minkowski_tensors(tri)

print("Rank-0 tensors (scalars):")
for name in ['w000', 'w100', 'w200', 'w300']:
    print(f"  {name} = {result[name]:.6f}")

print("\nRank-1 tensors (vectors, should be ~0 for a centred box):")
for name in ['w010', 'w110', 'w210', 'w310']:
    print(f"  {name} = {result[name]}")

Rank-0 tensors (scalars):
  w000 = 24.000000
  w100 = 17.333333
  w200 = 9.424778
  w300 = 4.188790

Rank-1 tensors (vectors, should be ~0 for a centred box):
  w010 = [0. 0. 0.]
  w110 = [0. 0. 0.]
  w210 = [0. 0. 0.]
  w310 = [0.00000000e+00 0.00000000e+00 1.11022302e-16]


## 3. Rank-2 tensors and eigensystems

Rank-2 functionals capture directional anisotropy. The eigensystem decomposition reveals the principal axes and their magnitudes.

In [5]:
print("Volume tensor (w020):")
print(result['w020'])

print("\nEigenvalues of w020:")
print(result['w020_eigvals'])

print("\nEigenvectors (columns) of w020:")
print(result['w020_eigvecs'])

Volume tensor (w020):
[[ 8.  0.  0.]
 [ 0. 18.  0.]
 [ 0.  0. 32.]]

Eigenvalues of w020:
[ 8. 18. 32.]

Eigenvectors (columns) of w020:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# All rank-2 tensor eigenvalues at a glance
print("Rank-2 tensor eigenvalues:")
print(f"{'Name':<8} {'λ₁':>12} {'λ₂':>12} {'λ₃':>12}")
print("-" * 48)
for name in ['w020', 'w120', 'w220', 'w320', 'w102', 'w202']:
    ev = result[f'{name}_eigvals']
    print(f"{name:<8} {ev[0]:12.6f} {ev[1]:12.6f} {ev[2]:12.6f}")

Rank-2 tensor eigenvalues:
Name               λ₁           λ₂           λ₃
------------------------------------------------
w020         8.000000    18.000000    32.000000
w120        11.111111    21.000000    33.777778
w220         8.028515    16.493361    26.529005
w320         4.188790     9.424778    16.755161
w102         4.000000     5.333333     8.000000
w202         2.617994     3.141593     3.665191


## 4. Using an explicit center

Position-dependent functionals (vectors and rank-2 tensors) depend on the choice of origin. Passing an explicit `center` shifts coordinates so the reference point is at the origin, which is useful for isolating shape anisotropy from positional effects.

In [7]:
# Shift the box away from the origin
offset = np.array([10.0, 20.0, 30.0])
shifted_verts = verts + offset

# Without center correction - vectors reflect the offset
result_no_center = pykarambola.minkowski_tensors(shifted_verts, faces)
print("w010 without center correction:", result_no_center['w010'])

# With explicit center correction - vectors reflect only shape
result_centered = pykarambola.minkowski_tensors(
    shifted_verts, faces, center=offset
)
print("w010 with center=offset:       ", result_centered['w010'])

w010 without center correction: [240. 480. 720.]
w010 with center=offset:        [0. 0. 0.]


## 5. Working with labelled surfaces

When your mesh has multiple bodies (e.g., grains, particles), pass a per-face `labels` array. Functionals are computed independently for each label.

In [8]:
# Load a mesh with labels
tri_labelled = pykarambola.parse_poly_file(
    '../tests/fixtures/two_boxes_sharing_vertex_with_labels.poly',
    with_labels=True,
)

print(f"Vertices:  {tri_labelled.n_vertices()}")
print(f"Triangles: {tri_labelled.n_triangles()}")

Vertices:  16
Triangles: 24


In [9]:
# Compute per-label functionals — labels are extracted from the Triangulation automatically
# Note: this fixture (two_boxes_sharing_vertex_with_labels.poly) has inverted face winding
# (inward normals) and a shared vertex between the two boxes (non-manifold geometry).
# pykarambola emits UserWarnings for both; the negative w000 is the expected signal
# for inverted winding — the true volume is abs(w000).
results = pykarambola.minkowski_tensors(tri_labelled)

for label, funcs in sorted(results.items()):
    print(f'\nLabel {label}:')
    print(f'  Volume (w000):       {funcs["w000"]:.4f}  <- inverted winding; true vol = {abs(funcs["w000"]):.4f}')
    print(f'  Surface area (w100): {funcs["w100"]:.4f}')
    print(f'  Euler char (w300):   {funcs["w300"]:.4f}')


Label 1:
  Volume (w000):       -24.0000  <- inverted winding; true vol = 24.0000
  Surface area (w100): 17.3333
  Euler char (w300):   3.1416

Label 2:
  Volume (w000):       -24.0000  <- inverted winding; true vol = 24.0000
  Surface area (w100): 17.3333
  Euler char (w300):   3.1416


/var/folders/zl/l0prjwwn0db0fm9nhs69bxgh0000gn/T/ipykernel_96821/159174887.py:6: UserWarning: Non-manifold mesh detected: results may be unreliable.
  results = pykarambola.minkowski_tensors(tri_labelled)
/Users/yajushikhurana/Desktop/pykarambola_ishiharalab_mac/pykarambola/pykarambola/api.py:475: UserWarning: Mesh contains vertices with zero or negative angle sum (isolated or degenerate triangles); their Gaussian curvature contribution is set to zero.
  raw_w300 = calculate_w300(surface) if (
/Users/yajushikhurana/Desktop/pykarambola_ishiharalab_mac/pykarambola/pykarambola/api.py:489: UserWarning: Mesh contains vertices with zero or negative angle sum (isolated or degenerate triangles); their contribution is set to zero.
  raw_w310 = calculate_w310(surface) if (
/Users/yajushikhurana/Desktop/pykarambola_ishiharalab_mac/pykarambola/pykarambola/api.py:522: UserWarning: Mesh contains vertices with zero or negative angle sum (isolated or degenerate triangles); their contribution is set to

### Passing labels as a NumPy array

Instead of loading a pre-labelled file, you can supply a per-face integer array directly.
Here we build two disconnected boxes programmatically and assign each a label.

In [10]:
def make_box(cx, cy, cz, a=1.0, b=1.0, c=1.0):
    """Return (verts, faces) for an axis-aligned box centred at (cx, cy, cz)."""
    ha, hb, hc = a / 2, b / 2, c / 2
    v = np.array([
        [cx-ha, cy-hb, cz-hc], [cx+ha, cy-hb, cz-hc],
        [cx+ha, cy+hb, cz-hc], [cx-ha, cy+hb, cz-hc],
        [cx-ha, cy-hb, cz+hc], [cx+ha, cy-hb, cz+hc],
        [cx+ha, cy+hb, cz+hc], [cx-ha, cy+hb, cz+hc],
    ], dtype=np.float64)
    f = np.array([
        [0,3,2],[0,2,1], [4,5,6],[4,6,7],
        [0,1,5],[0,5,4], [2,3,7],[2,7,6],
        [0,4,7],[0,7,3], [1,2,6],[1,6,5],
    ], dtype=np.int64)
    return v, f

# Box A: 2×2×2 cube on the left; Box B: 1×3×1 cuboid on the right
v1, f1 = make_box(-3, 0, 0, a=2, b=2, c=2)
v2, f2 = make_box(+3, 0, 0, a=1, b=3, c=1)

all_verts = np.vstack([v1, v2])
all_faces = np.vstack([f1, f2 + len(v1)])  # offset face indices for second box

# Explicit per-face label array
face_labels = np.array([1] * len(f1) + [2] * len(f2), dtype=np.int64)

results_labelled = pykarambola.minkowski_tensors(all_verts, all_faces, labels=face_labels)
for label, r in sorted(results_labelled.items()):
    print(f"Label {label}: volume={r['w000']:.3f}, area={r['w100']:.3f}")

Label 1: volume=8.000, area=8.000
Label 2: volume=3.000, area=4.667


### Auto-detecting connected components: `labels='auto'` and `return_count`

When your mesh has multiple disconnected bodies but you don't have a label array, pass `labels='auto'` — pykarambola will detect connected components via SciPy and number them 1, 2, ….
`return_count=True` appends the component count to the return value.

In [11]:
# labels='auto': no label array needed — components detected automatically
results_auto, n_objects = pykarambola.minkowski_tensors(
    all_verts, all_faces, labels='auto', return_count=True
)

print(f"Detected {n_objects} connected object(s)\n")
for label, r in sorted(results_auto.items()):
    print(f"Component {label}: volume={r['w000']:.3f}, area={r['w100']:.3f}")

Detected 2 connected object(s)

Component 1: volume=8.000, area=8.000
Component 2: volume=3.000, area=4.667


## 6. Computing from a 3D label image (voxel data)

If your data is a 3D voxel image (e.g., from a CT scan segmentation), use `minkowski_tensors_from_label_image()`. It internally runs marching cubes to create a triangulated surface.

**Requires:** `scikit-image`

In [12]:
# Create a synthetic 3D label image with a sphere
shape = (64, 64, 64)
z, y, x = np.mgrid[:shape[0], :shape[1], :shape[2]]
center = np.array(shape) / 2
radius = 20.0

dist = np.sqrt((x - center[2])**2 + (y - center[1])**2 + (z - center[0])**2)
label_image = np.zeros(shape, dtype=int)
label_image[dist <= radius] = 1

print(f"Image shape: {label_image.shape}")
print(f"Voxels in sphere: {np.sum(label_image == 1)}")

Image shape: (64, 64, 64)
Voxels in sphere: 33401


In [13]:
results = pykarambola.minkowski_tensors_from_label_image(label_image)

r = results[1]  # label 1
analytical_vol = 4 / 3 * np.pi * radius**3

print(f"Measured volume (w000):  {r['w000']:.1f}")
print(f"Analytical sphere vol:   {analytical_vol:.1f}")
print(f"Relative error:          {abs(r['w000'] - analytical_vol) / analytical_vol:.2%}")
analytical_area = 4 * np.pi * radius**2
print(f"\nMeasured area (w100):    {r['w100']:.1f}")
print(f"Analytical area (A/3):   {analytical_area/3:.1f}  (A = {analytical_area:.1f})")
print(f"Relative area error:     {abs(r['w100'] - analytical_area/3) / (analytical_area/3):.2%}  (higher than volume: staircase artefacts on voxel grid)")
print(f"Euler char (w300):       {r['w300']:.4f}")

Measured volume (w000):  33359.5
Analytical sphere vol:   33510.3
Relative error:          0.45%

Measured area (w100):    1817.6
Analytical area (A/3):   1675.5  (A = 5026.5)
Relative area error:     8.48%  (higher than volume: staircase artefacts on voxel grid)
Euler char (w300):       4.1888


Note: The voxelised sphere approximation improves with higher resolution (larger images).

## 7. Selecting specific functionals

For performance, you can request only the functionals you need.

In [14]:
# Only compute volume and surface area
result = pykarambola.minkowski_tensors(
    verts, faces, compute=['w000', 'w100']
)
print("Keys returned:", sorted(result.keys()))
print(f"Volume: {result['w000']:.4f}")
print(f"Area:   {result['w100']:.4f}")

Keys returned: ['w000', 'w100']
Volume: 24.0000
Area:   17.3333


In [15]:
# Compute everything including higher-order tensors and spherical Minkowski
result_all = pykarambola.minkowski_tensors(
    verts, faces, compute='all'
)
print("All keys:", sorted(result_all.keys()))
print(f"\nw103 shape (rank-3 tensor): {result_all['w103'].shape}")
print(f"w104 shape (rank-4 tensor): {result_all['w104'].shape}")
print(f"Spherical Minkowski ql:     {result_all['msm_ql']}")
print(f"Spherical Minkowski wl:     {result_all['msm_wl']}")

All keys: ['msm_ql', 'msm_wl', 'w000', 'w010', 'w020', 'w020_beta', 'w020_eigvals', 'w020_eigvecs', 'w020_trace', 'w020_trace_ratio', 'w100', 'w102', 'w102_beta', 'w102_eigvals', 'w102_eigvecs', 'w102_trace', 'w103', 'w104', 'w110', 'w120', 'w120_beta', 'w120_eigvals', 'w120_eigvecs', 'w120_trace', 'w120_trace_ratio', 'w200', 'w202', 'w202_beta', 'w202_eigvals', 'w202_eigvecs', 'w202_trace', 'w210', 'w220', 'w220_beta', 'w220_eigvals', 'w220_eigvecs', 'w220_trace', 'w220_trace_ratio', 'w300', 'w310', 'w320', 'w320_beta', 'w320_eigvals', 'w320_eigvecs', 'w320_trace', 'w320_trace_ratio']

w103 shape (rank-3 tensor): (3, 3, 3)
w104 shape (rank-4 tensor): (6, 6)
Spherical Minkowski ql:     [1.00000000e+00 7.24658058e-17 2.03519332e-01 1.15391292e-16
 7.74978526e-01 2.02043727e-16 4.01550250e-01 2.67813033e-16
 7.31907009e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
Spherical Minkowski wl:     [ 1.          0.         -0.102853    0.          0.41614917  0.
 -0.10613408  0.          0.

## 8. Low-level API: individual functional calculators

For maximum control, you can use the individual `calculate_w*` functions directly on a `Triangulation` object.

In [16]:
from pykarambola import Triangulation, calculate_w000, LABEL_UNASSIGNED

# Build a Triangulation from arrays
surface = Triangulation.from_arrays(verts, faces)

print(f"Vertices: {surface.n_vertices()}")
print(f"Triangles: {surface.n_triangles()}")

# Compute volume using the low-level calculator
raw_w000 = calculate_w000(surface)
# Returns dict[label] -> MinkValResult
for label, mink_val in raw_w000.items():
    print(f"\nLabel {label}: volume = {mink_val.result:.6f}")

Vertices: 8
Triangles: 12

Label 0: volume = 24.000000


## 9. Loading different file formats

In [17]:
# .off format
tri_off = pykarambola.parse_off_file('../tests/fixtures/cuboid.off')
print(f"OFF: {tri_off.n_vertices()} vertices, {tri_off.n_triangles()} triangles")

result_off = pykarambola.minkowski_tensors(tri_off)
print(f"  Volume: {result_off['w000']:.4f}")
print(f"  Area:   {result_off['w100']:.4f}")

OFF: 8 vertices, 12 triangles
  Volume: 4.0000
  Area:   5.1046


In [18]:
# .obj format
tri_obj = pykarambola.parse_obj_file('../tests/fixtures/box.obj')
print(f"OBJ: {tri_obj.n_vertices()} vertices, {tri_obj.n_triangles()} triangles")

result_obj = pykarambola.minkowski_tensors(tri_obj)
print(f"  Volume: {result_obj['w000']:.4f}")
print(f"  Area:   {result_obj['w100']:.4f}")

OBJ: 8 vertices, 12 triangles
  Volume: 24.0000
  Area:   17.3333


## 10. Derived scalar quantities: `_beta`, `_trace`, `_trace_ratio`

`compute='all'` includes three pykarambola-specific scalars for every rank-2 tensor:

| Key | Definition |
|-----|----------|
| `{name}_beta` | Anisotropy index — min\|λ\| / max\|λ\|; ranges 0 (maximally anisotropic) to 1 (isotropic) |
| `{name}_trace` | Matrix trace Tr(W) |
| `{name}_trace_ratio` | Tr(W) / paired Minkowski scalar (wX20 family only; e.g. `Tr(w020)/w000`) |

`compute_eigensystems=False` skips eigendecomposition for batch jobs that don't need eigenvectors.

> **NaN rows:** `_trace_ratio` is only defined for position-weighted tensors in the wX20 family
> (w020, w120, w220, w320). The normal-weighted tensors w102 and w202 have no natural paired
> Minkowski scalar, so their `_trace_ratio` is always `nan`.

In [19]:
# compute='all' returns _beta, _trace, _trace_ratio for each rank-2 tensor
result_all = pykarambola.minkowski_tensors(verts, faces, compute='all')

print(f"{'Tensor':<8}  {'beta':>8}  {'trace':>12}  {'trace_ratio':>13}")
print("-" * 48)
for name in ['w020', 'w120', 'w220', 'w320', 'w102', 'w202']:
    beta  = result_all[f'{name}_beta']
    trace = result_all[f'{name}_trace']
    tr    = result_all.get(f'{name}_trace_ratio', float('nan'))
    print(f"{name:<8}  {beta:8.4f}  {trace:12.6f}  {tr:13.6f}")

Tensor        beta         trace    trace_ratio
------------------------------------------------
w020        0.2500     58.000000       2.416667
w120        0.3289     65.888889       3.801282
w220        0.3026     51.050881       5.416667
w320        0.2500     30.368729       7.250000
w102        0.5000     17.333333            nan
w202        0.7143      9.424778            nan


In [20]:
# compute_eigensystems=False: skip eigendecomposition for batch jobs that don't need eigenvectors
result_no_eig = pykarambola.minkowski_tensors(verts, faces, compute_eigensystems=False)

has_eigvals = any('_eigvals' in k for k in result_no_eig)
print(f"_eigvals present: {has_eigvals}")        # False — skipped
print(f"w020 still computed: {'w020' in result_no_eig}")  # True — tensor itself is unaffected

_eigvals present: False
w020 still computed: True


## Summary

| Task | Function |
|---|---|
| Compute from arrays | `minkowski_tensors(verts, faces)` |
| Compute from parser result | `minkowski_tensors(tri)` |
| Compute from voxels | `minkowski_tensors_from_label_image(label_image)` |
| Load .poly file | `parse_poly_file(path)` |
| Load .off file | `parse_off_file(path)` |
| Load .obj file | `parse_obj_file(path)` |
| Load .glb file | `parse_glb_file(path)` |
| Per-label analysis | Pass `labels=` array, or pass a labelled `Triangulation` |
| Centroid correction | Pass `center='reference_centroid'` |
| Select functionals | Pass `compute=['w000', 'w100', ...]` |
| All functionals | Pass `compute='all'` |

In [21]:
help(pykarambola.minkowski_tensors)

Help on function minkowski_tensors in module pykarambola.api:

minkowski_tensors(
    verts: Union[numpy.ndarray, pykarambola.triangulation.Triangulation],
    faces=None,
    labels=None,
    center=None,
    center_per_label=True,
    compute='standard',
    compute_eigensystems=True,
    return_count=False
)
    Compute Minkowski tensors on a triangulated surface.

    Parameters
    ----------
    verts : (V, 3) array_like or Triangulation
        Vertex positions, or a ``Triangulation`` object returned by any parser
        (``parse_obj_file``, ``parse_off_file``, ``parse_poly_file``,
        ``parse_glb_file``). When a ``Triangulation`` is passed, ``faces``
        may be omitted and ``labels`` defaults to the triangulation's own
        label array (if any).
    faces : (F, 3) array_like or None
        Triangle vertex indices. Required when *verts* is an array; ignored
        (may be ``None``) when *verts* is a ``Triangulation``.
    labels : (F,) array_like, 'auto', or None
 